version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "stack-lab-ccoe-cleanup-001"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1gmbo6b8lrlez"
s3_prefix = "stack-lab-ccoe-cleanup-001"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
